// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.0
// Machine:  kommusoft-X75VD
// DateTime: 9/1/2013 2:18:24 PM
// UserName: kommusoft
// Input file <MiniZinc.bison - 9/1/2013 2:18:15 PM>

// options: lines

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace ZincOxide.MiniZinc {


}
